import { Address } from "viem";

// ArcaCore Contract ABI
export const arcaCoreABI = [
  {
    inputs: [
      { internalType: "uint8", name: "_defaultTraitSrength", type: "uint8" },
      { internalType: "uint8", name: "_defaultTraitAgility", type: "uint8" },
      {
        internalType: "uint8",
        name: "_deafaultTraitIntelligence",
        type: "uint8",
      },
      { internalType: "uint8", name: "_defaultTraitWillpower", type: "uint8" },
      {
        internalType: "uint8",
        name: "_defaultTraitManipulation",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "_deafaulTraitIntimidation",
        type: "uint8",
      },
      { internalType: "uint8", name: "_defaultTraitStealth", type: "uint8" },
      { internalType: "uint8", name: "_defaultTraitPerception", type: "uint8" },
      { internalType: "int8", name: "_deafultTraitMorality", type: "int8" },
      { internalType: "int8", name: "_defaultTraitReputation", type: "int8" },
      { internalType: "uint16", name: "_defaultTraitWealth", type: "uint16" },
      { internalType: "address", name: "_arkaToken", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AccessControlBadConfirmation", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "account", type: "address" },
      { internalType: "bytes32", name: "neededRole", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ArcCore__AgentAlreadyLive", type: "error" },
  { inputs: [], name: "ArcCore__InvalidAgentParams", type: "error" },
  { inputs: [], name: "ArcCore__OwnerAgentAlreadyExist", type: "error" },
  { inputs: [], name: "ArcCore__OwnlyAgentOwnerCanClaim", type: "error" },
  { inputs: [], name: "ArcaCore__AgentIsNotAlive", type: "error" },
  { inputs: [], name: "ArcaCore__CantKillAgentsWithMinRep", type: "error" },
  { inputs: [], name: "ArcaCore__CityAlreadyInitialised", type: "error" },
  { inputs: [], name: "ArcaCore__InvalidCityParams", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "agentName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "agentAddy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "enum ArcaCore.PERSONAS",
        name: "persona",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
      {
        components: [
          { internalType: "uint8", name: "strength", type: "uint8" },
          { internalType: "uint8", name: "agility", type: "uint8" },
          { internalType: "uint8", name: "intelligence", type: "uint8" },
          { internalType: "uint8", name: "willpower", type: "uint8" },
          { internalType: "uint8", name: "manipulation", type: "uint8" },
          { internalType: "uint8", name: "intimidation", type: "uint8" },
          { internalType: "uint8", name: "stealth", type: "uint8" },
          { internalType: "uint8", name: "perception", type: "uint8" },
          { internalType: "int8", name: "morality", type: "int8" },
          { internalType: "int8", name: "reputation", type: "int8" },
          { internalType: "uint16", name: "wealth", type: "uint16" },
        ],
        indexed: false,
        internalType: "struct ArcaCore.AgentTraits",
        name: "defaultTraits",
        type: "tuple",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "agentDob",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "reputationScore",
        type: "uint16",
      },
    ],
    name: "AgentCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "agentAddy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "AgentKilled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      { indexed: false, internalType: "string", name: "name", type: "string" },
      {
        indexed: false,
        internalType: "uint32",
        name: "maxPopulation",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "createdAt",
        type: "uint128",
      },
    ],
    name: "CityCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_REPUTATION_SCORE",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "addressToAgent",
    outputs: [
      { internalType: "string", name: "agentName", type: "string" },
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "agentAddy", type: "address" },
      {
        internalType: "enum ArcaCore.PERSONAS",
        name: "persona",
        type: "uint8",
      },
      { internalType: "uint256", name: "balance", type: "uint256" },
      {
        components: [
          { internalType: "uint8", name: "strength", type: "uint8" },
          { internalType: "uint8", name: "agility", type: "uint8" },
          { internalType: "uint8", name: "intelligence", type: "uint8" },
          { internalType: "uint8", name: "willpower", type: "uint8" },
          { internalType: "uint8", name: "manipulation", type: "uint8" },
          { internalType: "uint8", name: "intimidation", type: "uint8" },
          { internalType: "uint8", name: "stealth", type: "uint8" },
          { internalType: "uint8", name: "perception", type: "uint8" },
          { internalType: "int8", name: "morality", type: "int8" },
          { internalType: "int8", name: "reputation", type: "int8" },
          { internalType: "uint16", name: "wealth", type: "uint16" },
        ],
        internalType: "struct ArcaCore.AgentTraits",
        name: "agentTraits",
        type: "tuple",
      },
      { internalType: "uint128", name: "agentDOB", type: "uint128" },
      { internalType: "bool", name: "isAlive", type: "bool" },
      { internalType: "uint16", name: "reputationScore", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_agentAddy", type: "address" }],
    name: "claimAgentRewards",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_agentnName", type: "string" },
      { internalType: "address", name: "_agentAddy", type: "address" },
      { internalType: "uint16", name: "_reputationScore", type: "uint16" },
    ],
    name: "createAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "uint128", name: "_treasuryBalance", type: "uint128" },
      { internalType: "uint32", name: "_maxPopulation", type: "uint32" },
    ],
    name: "createCity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_agentAddy", type: "address" }],
    name: "killAgent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "ownerToAgent",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "callerConfirmation", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawAdminFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

// Replace with actual contract address
export const ARCA_CORE_ADDRESS: Address =
  "0xf61f0B43AA5E757a77564FD88D2fbB566FFfbF79";
